#!/usr/bin/perl

# http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Last Change:  2011/10/16 17:20:37 .

use warnings;
use strict;

my $num = 4_000_000;
my @terms = (1, 2);

my $result = 0;
while (1) {
    $result += $terms[-1] if ($terms[-1] % 2 == 0);

    my $i = scalar @terms;
    push @terms, $terms[$i - 2] + $terms[$i - 1];
    #warn '  term '.$terms[$i];
    last if ($num <= $terms[-1]);
}

print 'result: '.$result."\n";
